import argparse, glob, os
from consts import *

def parse_arguments():
    parser = argparse.ArgumentParser(description='counter')
    parser.add_argument('dataset', type=str, default='setA', help='Select dataset (setA, setC)')
    args = parser.parse_args()

    # Sanitizing arguments
    assert args.dataset in ['setA', 'setC'], 'Invalid dataset: "%s"'%(args.dataset)

    return args

################################

def is_valid_data(data):
    if len(data.split()) != 2:
        return False
    return True

def read_code_size_data(filepath):
    with open(filepath) as fd:
        data = fd.read()
        if not is_valid_data(data):
            return None

        old_size, new_size = data.split()
        old_size = int(old_size)
        new_size = int(new_size)
        return (new_size - old_size) / old_size

# Collect data generated by 4_get_code_size_overhead.py.
def collect_data(args):
    data = {}
    for package in PACKAGES:
        stat_files = os.path.join('stat', 'size', args.dataset, '%s_*' % package)
        for filepath in glob.glob(stat_files):
            overhead = read_code_size_data(filepath)
            if overhead is None:
                continue

            if package not in data:
                data[package] = 0, 0

            num_bins, sum_overhead = data[package]
            num_bins += 1
            sum_overhead += overhead
            data[package] = num_bins, sum_overhead

    return data

################################

# Report the percentage of average code size overheads for Section 4.3.1 of our
# paper.
def report(data):
    print(FMT_CODE_HEADER)
    print(FMT_LINE)

    total_num_bins = 0
    total_overhead = 0.0
    for package in PACKAGES:
        if package not in data:
            continue

        num_bins, overhead = data[package]
        total_num_bins += num_bins
        total_overhead += overhead
        if num_bins > 0:
            avg_overhead = overhead / num_bins * 100
            print(FMT_OVERHEAD % (package, num_bins, avg_overhead)) # Report individual data per package

    if total_num_bins > 0:
        print(FMT_LINE)
        total_avg_overhead = total_overhead / total_num_bins * 100
        print(FMT_OVERHEAD % ('[+]All', total_num_bins, total_avg_overhead)) # Report overall data

if __name__ == '__main__':
    args = parse_arguments()
    data = collect_data(args)
    report(data)
